# SwiftLint Configuration for PhotoScreensaver

# Paths to include/exclude
included:
  - PhotoScreensaver
excluded:
  - build
  - .build
  - .git

# Enabled rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - modifier_order
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Disabled rules
disabled_rules:
  - trailing_whitespace # Let formatters handle this
  - line_length # Some comments/strings need to be longer

# Rule configurations
identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - x
    - y

type_name:
  min_length: 3
  max_length: 50

function_body_length:
  warning: 80
  error: 120

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

# Analyzer rules (require building the project)
analyzer_rules:
  - unused_declaration
  - unused_import
